---
branch-protection-check-name: Change log entry
action-hints:
  check-title-prefix: "Chronographer: "
  external-docs-url: https://pip-tools.rtfd.io/en/latest/contributing/
  inline-markdown: |
    See [the changelog contribution docs] ...
    [the changelog contribution docs]:
    https://pip-tools.readthedocs.io/en/latest/contributing/
  enforce-name:
  suffix: .md
...
