categories:
  - title: "Backwards Incompatible Changes"
    labels:
      - "backwards incompatible"

  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
      # usually combined with enhancement (avoid double listing)
      - "deprecation"

  - title: "Bug Fixes"
    labels:
      - "bug"
      - "bug fix"

  - title: "Other Changes"
    labels:
      - "dependency"
      - "docs"
      - "trivial"
      - "maintenance"

exclude-labels:
  - "skip-changelog"
template: |
  $CHANGES
