# Format and labels used aim to match those used by Ansible project
categories:
  - title: 'Major Changes'
    labels:
      - 'major'  # c6476b
  - title: 'Minor Changes'
    labels:
      - 'feature'  # 006b75
      - 'enhancement'  # ededed
      - 'refactoring'
  - title: 'Bugfixes'
    labels:
      - 'bug'  # fbca04
  - title: 'Deprecations'
    labels:
      - 'deprecated'  # fef2c0
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES
