- id: pip-compile
  name: pip-compile
  description: Automatically compile requirements.
  entry: pip-compile
  language: python
  files: ^pyproject\.toml|requirements\.(in|txt)$
  pass_filenames: false
