name: release-drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - 'releases/**'
      - 'stable/**'

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
