name: release-drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - "releases/**"
      - "stable/**"

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    if: github.repository == 'jazzband/pip-tools'
    runs-on: ubuntu-latest
    steps:
      # Drafts your next release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
